<?php

header("Access-Control-Allow-Origin: http://localhost:5173");
header("Access-Control-Allow-Headers: Content-Type");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Content-Type: application/json");

ob_start();
ini_set("display_errors", 0);

include("../../config/db.php");

if ($_SERVER["REQUEST_METHOD"] === "OPTIONS") {
    http_response_code(200);
    exit;
}

try {

    if ($_SERVER["REQUEST_METHOD"] !== "POST") {
        throw new Exception(
            "Only POST method is allowed"
        );
    }

    $input = json_decode(
        file_get_contents("php://input"),
        true
    );

    if (!is_array($input)) {
        throw new Exception(
            "Invalid request data"
        );
    }

    $user_id =
        $input["user_id"] ?? null;

    $title =
        trim($input["title"] ?? "");

    $audience =
        trim($input["audience"] ?? "Students");

    $class_name =
        trim($input["class_name"] ?? "ALL");

    $section =
        trim($input["section"] ?? "ALL");

    $notice_type =
        trim($input["notice_type"] ?? "General");

    $priority =
        trim($input["priority"] ?? "Medium");

    $description =
        trim($input["description"] ?? "");

    $expiry_date =
        !empty($input["expiry_date"])
            ? trim($input["expiry_date"])
            : null;

    /*
     * Validate User ID
     */
    if (!$user_id || !is_numeric($user_id)) {
        throw new Exception(
            "Invalid user ID"
        );
    }

    $user_id = (int)$user_id;

    /*
     * Verify Principal
     */
    $userQuery = "
        SELECT
            id,
            full_name,
            role
        FROM users
        WHERE id = ?
        LIMIT 1
    ";

    $userStmt =
        $conn->prepare($userQuery);

    if (!$userStmt) {
        throw new Exception(
            "Unable to verify user: " .
            $conn->error
        );
    }

    $userStmt->bind_param(
        "i",
        $user_id
    );

    $userStmt->execute();

    $user =
        $userStmt
            ->get_result()
            ->fetch_assoc();

    $userStmt->close();

    if (!$user) {
        throw new Exception(
            "User not found"
        );
    }

    if (
        strtolower(
            trim($user["role"])
        ) !== "principal"
    ) {
        throw new Exception(
            "Only principals can create school notices"
        );
    }

    /*
     * Validate Notice
     */
    if ($title === "") {
        throw new Exception(
            "Notice title is required"
        );
    }

    if ($description === "") {
        throw new Exception(
            "Notice content is required"
        );
    }

    /*
     * Validate Audience
     */
    $audienceMap = [
        "Students" => "Student",
        "Parents" => "Parent",
        "Teachers" => "Teacher",
        "All" => "All"
    ];

    if (!isset($audienceMap[$audience])) {
        throw new Exception(
            "Invalid notice audience"
        );
    }

    $noticeFor =
        $audienceMap[$audience];

    /*
     * Validate Priority
     */
    $allowedPriorities = [
        "Low",
        "Medium",
        "High"
    ];

    if (
        !in_array(
            $priority,
            $allowedPriorities,
            true
        )
    ) {
        $priority = "Medium";
    }

    /*
     * Normalize Class
     */
    $class_name =
        strtoupper($class_name) === "ALL"
            ? "ALL"
            : $class_name;

    /*
     * Normalize Section
     */
    $section =
        strtoupper($section) === "ALL"
            ? "ALL"
            : $section;

    /*
     * Class/Section required only
     * for Students and Parents
     */
    if (
        (
            $noticeFor === "Student" ||
            $noticeFor === "Parent"
        ) &&
        $class_name === ""
    ) {
        throw new Exception(
            "Class is required"
        );
    }

    /*
     * Begin transaction
     */
    $conn->begin_transaction();

    /*
     * Create Notice
     *
     * created_at is automatically
     * generated by MySQL.
     */
    $noticeQuery = "
        INSERT INTO notices
        (
            title,
            description,
            notice_type,
            priority,
            notice_for,
            created_by,
            created_role,
            publish_date,
            expiry_date,
            status
        )
        VALUES
        (
            ?,
            ?,
            ?,
            ?,
            ?,
            ?,
            'principal',
            NOW(),
            ?,
            'Published'
        )
    ";

    $noticeStmt =
        $conn->prepare($noticeQuery);

    if (!$noticeStmt) {
        throw new Exception(
            "Unable to prepare notice query: " .
            $conn->error
        );
    }

    $noticeStmt->bind_param(
        "sssssis",
        $title,
        $description,
        $notice_type,
        $priority,
        $noticeFor,
        $user_id,
        $expiry_date
    );

    if (!$noticeStmt->execute()) {
        throw new Exception(
            "Failed to save notice: " .
            $noticeStmt->error
        );
    }

    $noticeId =
        (int)$noticeStmt->insert_id;

    $noticeStmt->close();

    /*
     * Recipient list
     */
    $recipients = [];

    /*
     * STUDENTS
     */
    if ($noticeFor === "Student") {

        if ($class_name === "ALL") {

            $query = "
                SELECT
                    id,
                    user_id
                FROM students
                WHERE status = 'Active'
                  AND user_id IS NOT NULL
            ";

            $stmt =
                $conn->prepare($query);

        } elseif ($section === "ALL") {

            $query = "
                SELECT
                    id,
                    user_id
                FROM students
                WHERE class = ?
                  AND status = 'Active'
                  AND user_id IS NOT NULL
            ";

            $stmt =
                $conn->prepare($query);

        } else {

            $query = "
                SELECT
                    id,
                    user_id
                FROM students
                WHERE class = ?
                  AND section = ?
                  AND status = 'Active'
                  AND user_id IS NOT NULL
            ";

            $stmt =
                $conn->prepare($query);
        }

        if (!$stmt) {
            throw new Exception(
                "Unable to find students: " .
                $conn->error
            );
        }

        if ($class_name === "ALL") {

            $stmt->execute();

        } elseif ($section === "ALL") {

            $stmt->bind_param(
                "s",
                $class_name
            );

            $stmt->execute();

        } else {

            $stmt->bind_param(
                "ss",
                $class_name,
                $section
            );

            $stmt->execute();
        }

        $result =
            $stmt->get_result();

        while (
            $row =
                $result->fetch_assoc()
        ) {

            $recipients[] = [
                "target_type" =>
                    "student",

                "target_role" =>
                    "student",

                "target_id" =>
                    (int)$row["id"],

                "user_id" =>
                    (int)$row["user_id"]
            ];
        }

        $stmt->close();
    }

    /*
     * PARENTS
     */
    elseif ($noticeFor === "Parent") {

        if ($class_name === "ALL") {

            $query = "
                SELECT
                    p.student_id,
                    p.user_id
                FROM parents p
                INNER JOIN students s
                    ON s.id = p.student_id
                WHERE s.status = 'Active'
                  AND p.user_id IS NOT NULL
            ";

            $stmt =
                $conn->prepare($query);

        } elseif ($section === "ALL") {

            $query = "
                SELECT
                    p.student_id,
                    p.user_id
                FROM parents p
                INNER JOIN students s
                    ON s.id = p.student_id
                WHERE s.class = ?
                  AND s.status = 'Active'
                  AND p.user_id IS NOT NULL
            ";

            $stmt =
                $conn->prepare($query);

        } else {

            $query = "
                SELECT
                    p.student_id,
                    p.user_id
                FROM parents p
                INNER JOIN students s
                    ON s.id = p.student_id
                WHERE s.class = ?
                  AND s.section = ?
                  AND s.status = 'Active'
                  AND p.user_id IS NOT NULL
            ";

            $stmt =
                $conn->prepare($query);
        }

        if (!$stmt) {
            throw new Exception(
                "Unable to find parents: " .
                $conn->error
            );
        }

        if ($class_name === "ALL") {

            $stmt->execute();

        } elseif ($section === "ALL") {

            $stmt->bind_param(
                "s",
                $class_name
            );

            $stmt->execute();

        } else {

            $stmt->bind_param(
                "ss",
                $class_name,
                $section
            );

            $stmt->execute();
        }

        $result =
            $stmt->get_result();

        while (
            $row =
                $result->fetch_assoc()
        ) {

            $recipients[] = [
                "target_type" =>
                    "student",

                "target_role" =>
                    "parent",

                "target_id" =>
                    (int)$row["student_id"],

                "user_id" =>
                    (int)$row["user_id"]
            ];
        }

        $stmt->close();
    }

    /*
     * TEACHERS
     */
    elseif ($noticeFor === "Teacher") {

        $query = "
            SELECT
                id
            FROM users
            WHERE LOWER(role) = 'teacher'
        ";

        $stmt =
            $conn->prepare($query);

        if (!$stmt) {
            throw new Exception(
                "Unable to find teachers: " .
                $conn->error
            );
        }

        $stmt->execute();

        $result =
            $stmt->get_result();

        while (
            $row =
                $result->fetch_assoc()
        ) {

            $teacherUserId =
                (int)$row["id"];

            if ($teacherUserId === $user_id) {
                continue;
            }

            $recipients[] = [
                "target_type" =>
                    "teacher",

                "target_role" =>
                    "teacher",

                "target_id" =>
                    $teacherUserId,

                "user_id" =>
                    $teacherUserId
            ];
        }

        $stmt->close();
    }

    /*
     * ENTIRE SCHOOL
     */
    elseif ($noticeFor === "All") {

        /*
         * Students
         */
        $query = "
            SELECT
                id,
                user_id
            FROM students
            WHERE status = 'Active'
              AND user_id IS NOT NULL
        ";

        $stmt =
            $conn->prepare($query);

        if (!$stmt) {
            throw new Exception(
                "Unable to find students"
            );
        }

        $stmt->execute();

        $result =
            $stmt->get_result();

        while (
            $row =
                $result->fetch_assoc()
        ) {

            $recipients[] = [
                "target_type" =>
                    "student",

                "target_role" =>
                    "student",

                "target_id" =>
                    (int)$row["id"],

                "user_id" =>
                    (int)$row["user_id"]
            ];
        }

        $stmt->close();

        /*
         * Parents
         */
        $query = "
            SELECT DISTINCT
                p.student_id,
                p.user_id
            FROM parents p
            INNER JOIN students s
                ON s.id = p.student_id
            WHERE s.status = 'Active'
              AND p.user_id IS NOT NULL
        ";

        $stmt =
            $conn->prepare($query);

        if (!$stmt) {
            throw new Exception(
                "Unable to find parent users"
            );
        }

        $stmt->execute();

        $result =
            $stmt->get_result();

        while (
            $row =
                $result->fetch_assoc()
        ) {

            $recipients[] = [
                "target_type" =>
                    "student",

                "target_role" =>
                    "parent",

                "target_id" =>
                    (int)$row["student_id"],

                "user_id" =>
                    (int)$row["user_id"]
            ];
        }

        $stmt->close();

        /*
         * Teachers
         */
        $query = "
            SELECT
                id
            FROM users
            WHERE LOWER(role) = 'teacher'
        ";

        $stmt =
            $conn->prepare($query);

        if (!$stmt) {
            throw new Exception(
                "Unable to find teacher users"
            );
        }

        $stmt->execute();

        $result =
            $stmt->get_result();

        while (
            $row =
                $result->fetch_assoc()
        ) {

            $teacherUserId =
                (int)$row["id"];

            if ($teacherUserId === $user_id) {
                continue;
            }

            $recipients[] = [
                "target_type" =>
                    "teacher",

                "target_role" =>
                    "teacher",

                "target_id" =>
                    $teacherUserId,

                "user_id" =>
                    $teacherUserId
            ];
        }

        $stmt->close();

        /*
         * Admins
         */
        $query = "
            SELECT
                id
            FROM users
            WHERE LOWER(role) = 'admin'
        ";

        $stmt =
            $conn->prepare($query);

        if ($stmt) {

            $stmt->execute();

            $result =
                $stmt->get_result();

            while (
                $row =
                    $result->fetch_assoc()
            ) {

                $adminUserId =
                    (int)$row["id"];

                if ($adminUserId === $user_id) {
                    continue;
                }

                $recipients[] = [
                    "target_type" =>
                        "role",

                    "target_role" =>
                        "admin",

                    "target_id" =>
                        $adminUserId,

                    "user_id" =>
                        $adminUserId
                ];
            }

            $stmt->close();
        }
    }

    /*
     * Remove duplicate recipients
     */
    $uniqueRecipients = [];

    foreach ($recipients as $recipient) {

        $recipientUserId =
            (int)$recipient["user_id"];

        if (
            !isset(
                $uniqueRecipients[
                    $recipientUserId
                ]
            )
        ) {

            $uniqueRecipients[
                $recipientUserId
            ] = $recipient;
        }
    }

    $recipients =
        array_values(
            $uniqueRecipients
        );

    /*
     * No recipient
     */
    if (count($recipients) === 0) {

        throw new Exception(
            "No active recipients found for the selected audience"
        );
    }

    /*
     * Target insert
     */
    $targetQuery = "
        INSERT INTO notice_targets
        (
            notice_id,
            target_type,
            target_role,
            target_id
        )
        VALUES
        (?, ?, ?, ?)
    ";

    $targetStmt =
        $conn->prepare($targetQuery);

    if (!$targetStmt) {
        throw new Exception(
            "Unable to prepare target query: " .
            $conn->error
        );
    }

    /*
     * Notification insert
     *
     * created_at will automatically
     * store actual received time.
     */
    $notificationQuery = "
        INSERT INTO notifications
        (
            notice_id,
            user_id,
            is_read,
            read_at
        )
        VALUES
        (?, ?, 0, NULL)
    ";

    $notificationStmt =
        $conn->prepare(
            $notificationQuery
        );

    if (!$notificationStmt) {
        throw new Exception(
            "Unable to prepare notification query: " .
            $conn->error
        );
    }

    /*
     * Save targets + notifications
     */
    foreach ($recipients as $recipient) {

        $targetId =
            $recipient["target_id"];

        $targetStmt->bind_param(
            "issi",
            $noticeId,
            $recipient["target_type"],
            $recipient["target_role"],
            $targetId
        );

        if (!$targetStmt->execute()) {
            throw new Exception(
                "Failed to save notice target: " .
                $targetStmt->error
            );
        }

        $recipientUserId =
            (int)$recipient["user_id"];

        $notificationStmt->bind_param(
            "ii",
            $noticeId,
            $recipientUserId
        );

        if (!$notificationStmt->execute()) {
            throw new Exception(
                "Failed to create notification: " .
                $notificationStmt->error
            );
        }
    }

    $targetStmt->close();
    $notificationStmt->close();

    /*
     * Get actual DB timestamp
     */
    $timeQuery = "
        SELECT
            created_at,
            publish_date
        FROM notices
        WHERE id = ?
        LIMIT 1
    ";

    $timeStmt =
        $conn->prepare($timeQuery);

    $createdAt = null;
    $publishDate = null;

    if ($timeStmt) {

        $timeStmt->bind_param(
            "i",
            $noticeId
        );

        $timeStmt->execute();

        $timeRow =
            $timeStmt
                ->get_result()
                ->fetch_assoc();

        if ($timeRow) {

            $createdAt =
                $timeRow["created_at"];

            $publishDate =
                $timeRow["publish_date"];
        }

        $timeStmt->close();
    }

    /*
     * Commit
     */
    $conn->commit();

    ob_clean();

    echo json_encode([
        "status" => true,
        "message" =>
            "Principal notice published successfully",
        "notice_id" =>
            $noticeId,
        "recipient_count" =>
            count($recipients),
        "sent_at" =>
            $createdAt,
        "published_at" =>
            $publishDate
    ]);

} catch (Exception $e) {

    if (isset($conn)) {
        try {
            $conn->rollback();
        } catch (Throwable $ignored) {
        }
    }

    ob_clean();

    http_response_code(400);

    echo json_encode([
        "status" => false,
        "message" =>
            $e->getMessage()
    ]);
}
?>